CREATE TABLE LIBRO(
    ID NUMERIC(4) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(220) NOT NULL UNIQUE,
    AUTOR VARCHAR2(280) NOT NULL,
    ESTADO CHAR(1) DEFAULT '1'
);

CREATE SEQUENCE SEQ_LIBRO;

INSERT INTO LIBRO(ID,NOMBRE,AUTOR)
VALUES (SEQ_LIBRO.NEXTVAL, 'RESTful Java with JAX-RS 2.0: Designing and Developing Distributed Web Services',
'Bill Burke');

INSERT INTO LIBRO(ID,NOMBRE,AUTOR)
VALUES (SEQ_LIBRO.NEXTVAL, 'Building RESTful Web Services with Java EE 8: Create modern RESTful web services with the Java EE 8 API',
'Mario-Leander Reimer');

COMMIT;

SELECT ID,NOMBRE,AUTOR,ESTADO FROM LIBRO;